name: run 🚀 Weekly Notion Updater.py

on:
  schedule:
    - cron: '0 0 * * 3' # At 00:00 on Wednesday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: execute py script # run event-scraper.py
        env:
          SECRET_NotionToken: ${{ secrets.SECRET_NOTIONTOKEN }}
          SECRET_NotionDatabaseLink: ${{ secrets.SECRET_NOTIONDATABASELINK }}
        run: python event-scraper.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main